on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["current", "8.0"]
        racket-variant: ["CS"]
    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: x64
          distribution: minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
          dest: '"${HOME}/racketdist-${{ matrix.racket-variant }}"'
          local_catalogs: $GITHUB_WORKSPACE
          sudo: never
      - name: Installing mintexpp and its dependencies
        run: raco pkg install --no-docs --auto mintexpp
      - name: Compiling mintexpp and building its docs
        run: raco setup --check-pkg-deps mintexpp-reader-lib mintexpp-lib mintexpp-tex-lib mintexpp
      - name: Testing mintexpp
        run: raco test -x -p mintexpp
