on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["current"]
        racket-variant: ["CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing mintextpp and its dependencies
        run: raco pkg install --no-docs --auto --name mintextpp
      - name: Compiling mintextpp and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps mintextpp
      - name: Testing mintextpp
        run: raco test -x -p mintextpp
